export default {
    products:[
        {
            _id: '1',
            name: 'Hope',
            image: '/images/1.jpg',
            price: 25,
            section: 'Religion',
            rating: 4.5,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '2',
            name: 'Lion',
            image: '/images/2.jpg',
            price: 30,
            section: 'Religion',
            rating: 4.0,
            numReviews: 7,
            countInStock: 4,
        },
        {
            _id: '3',
            name: 'Mandala',
            image: '/images/3.jpg',
            price: 55,
            section: 'Religion',
            rating: 4.9,
            numReviews: 7,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Mountain View',
            image: '/images/4.jpg',
            price: 35,
            section: 'Nature',
            rating: 4.5,
            numReviews: 13,
            countInStock: 8,
        },
        {
            _id: '5',
            name: 'Floral',
            image: '/images/5.jpg',
            price: 20,
            section: 'Religion',
            rating: 4.2,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '6',
            name: 'Floral Tracing',
            image: '/images/6.jpg',
            price: 15,
            section: 'Religion',
            rating: 3.5,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '7',
            name: 'Work',
            image: '/images/7.jpg',
            price: 30,
            section: 'Religion',
            rating: 3.0,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '8',
            name: 'Robots',
            image: '/images/8.jpg',
            price: 60,
            section: 'Religion',
            rating: 4.8,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '9',
            name: 'Be Happy',
            image: '/images/9.jpg',
            price: 10,
            section: 'Religion',
            rating: 2.5,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '10',
            name: 'Diamond',
            image: '/images/10.jpg',
            price: 80,
            section: 'Religion',
            rating: 5.0,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '11',
            name: 'Be Brave',
            image: '/images/11.jpg',
            price: 35,
            section: 'Religion',
            rating: 4.0,
            numReviews: 10,
            countInStock: 2,
        },
        {
            _id: '12',
            name: 'Forest Magic',
            image: '/images/12.jpg',
            price: 30,
            section: 'Religion',
            rating: 2.5,
            numReviews: 10,
            countInStock: 2,
        }     

]}